
---
 
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mongo-demo
    labels:
        app: mongo-demo
        type: polivalente
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mongo-demo
            type: polivalente
    template:
        metadata:
            labels:
                app: mongo-demo
                type: polivalente
        spec:
            containers:
                - name: mongo-demo-container
                  image: trow.kube-public:31000/mongo-demo
                  ports:
                  - containerPort: 8080
                    name: mongo-demo-port
                  env:
                    - name: HOSTNAME
                      valueFrom:
                        configMapKeyRef:
                            name: mongo-config
                            key: hostname
                    - name: USERNAME
                      valueFrom:
                        secretKeyRef:
                            name: mongo-user
                            key: username
                    - name: PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: mongo-user
                            key: password
--- 

apiVersion: v1
kind: Service
metadata:
    labels:
        app: mongo-demo
        
    name: mongo-demo-svc-add
spec:
    selector:
        app: mongo-demo
        type: polivalente
    type: NodePort
    ports:
        - port: 8080
          targetPort: 8080
          nodePort: 31111