---
- name: Disabling Swap on all nodes
  shell: swapoff -a

- name: Commenting Swap entries in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '(^/.*swap*)'
    replace: '# \1'

- name: Add IPs to /etc/hosts on master and workers
  lineinfile:
     dest: /etc/hosts
     regexp: '.*{{ item }}$'
     line: "{{ hostvars[item].ansible_host }} {{item}}"
     state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"

- name: ensure net.bridge.bridge-nf-call-iptables is set to 1
  lineinfile:
     dest: /etc/sysctl.d/k8s.conf
     line: 
       - net.bridge.bridge-nf-call-iptables = 1
       - net.bridge.bridge-nf-call-ip6tables = 1
     state: present
     create: yes

- name: Download the Google Cloud public signing key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: ADD the Kubernetes apt repository
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main" 
    state: present
    filename: kubernetes.list

- name: Install kubernetes packages
  apt: 
    name: 
      - kubelet=1.19.0* # {{ inst_version }}*
      - kubeadm=1.19.0* #{{ inst_version }}*
      - kubectl=1.19.0* #{{ inst_version }}*
    state: present 


- name: enable Kubelet
  systemd: 
    name: kubelet
    state: started
    enabled: yes

