---
- name: Install python
  apt:
    name:
      - python3
      - python
    state: present 
    update_cache: yes

- name: Install pip
  apt:
    name:
      #- python-pip
      - python3-pip
    state: present 
