
- name: Install apt-transport-https 
  apt:
   name: 
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - software-properties-common
    - lsb-release
   state: latest
   update_cache: yes

- name: Add apt GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable

- name: Install Docker
  become_user: root
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Start docker daemon
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Add vagrant user to docker group
  user:
   name: vagrant
   group: docker

  

