---

apiVersion: v1
kind: Service
metadata:
  name: mongo-external-service
spec:
  type: NodePort
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      nodePort: 30017
      targetPort: 27017