---

apiVersion: v1
kind: Service
metadata:
  name: mongo-external-service
spec:
  type: NodePort
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      nodePort: 30017
      targetPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-external-service
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      nodePort: 30036
      targetPort: 3306
